# @package __global__

classifier_free_guidance:
  training_dropout: 0.3  # dropout of all conditions
  inference_coef: 3.0

attribute_dropout:
  text: {}
  wav:
    self_wav: 0.3  # independent dropout of drums

fuser:
  cross_attention_pos_emb: false
  cross_attention_pos_emb_scale: 1
  sum: []
  prepend: []
  cross: [description]
  ignore: [self_wav]
  input_interpolate: []

conditioners:
  self_wav:
    model: drum_latents
    drum_latents:
      sample_rate: ${sample_rate}
      out_dim: 2
      blurring_factor: 3
      cache_path: null

  description:
    model: t5
    t5:
      name: t5-base
      finetune: false
      word_dropout: 0.3
      normalize_text: false

dataset:
  train:
    merge_text_p: 0.25
    drop_desc_p: 0.5
    drop_other_p: 0.5
